services:
  - type: web
    name: mpesa-payment-server
    env: node
    plan: free
    buildCommand: cd server && npm install && npx prisma generate
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_ENVIRONMENT
        value: sandbox
      - key: MPESA_BUSINESS_SHORT_CODE
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_INITIATOR_NAME
        sync: false
      - key: MPESA_SECURITY_CREDENTIAL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health